### ISSUE TITLE
[NEW] Support exzrankwithscore command

### ISSUE THREAD

**Issue by yangbodong22011** [alibaba/TairZset#16]
Syntax
```
exzrankwithscore key
```
Array reply.
Return rank and score.

**Comment by yangbodong22011** [comment]
Please follow the result here and keep it consistent with its syntax: https://github.com/redis/redis/issues/11111

**Comment by RinChanNOWWW** [comment]
> Possible command formats:
> 1. z[rev]rank key member [withscore]
> 2. z[rev]rankwithscore key

So, what format should we use?

**Comment by yangbodong22011** [comment]
> > Possible command formats:
> > 
> > 1. z[rev]rank key member [withscore]
> > 2. z[rev]rankwithscore key
> 
> So, what format should we use?

Let's wait for feedback from the Redis community on this issue to be consistent with it.

**Comment by chenyang8094** [comment]
@RinChanNOWWW https://github.com/redis/redis/pull/11235
