### ISSUE TITLE
[ASoC]新命令开发支持

### ISSUE THREAD

**Issue by chenyang8094** [alibaba/TairZset#4]
# 活动官网
https://asoc2022.opensource.alibaba.com/

# 题目描述
TairZset作为redis原生zset的一个多增增强结构，前期只实现了一些基本的命令， 还有部分命令（使用频率相对较低）没有支持，
为了更好的对齐redis原生zset语义，需要补全这些命令的实现和对应的测试。

# 任务目标
1、开发支持EXZUNIONSTORE、EXZUNION、EXZSCAN、EXZDIFF、EXZDIFFSTORE、EXZINTER、EXZINTERSTORE、EXZRANDMEMBER、EXZMSCORE等确实命令（对齐到redis 5.0版本即可）
2、添加对应的tcl测试

# 项目技术要求
熟悉c、tcl，了解redis zset实现原理

# 题目难度
中

# 导师信息
Qu Dong ，@[chenyang8094](https://github.com/chenyang8094)，ASoC Mentor, [redis](https://github.com/redis/redis) contributor.
[chenyangyang.cy@alibaba-inc.com](mailto:chenyangyang.cy@alibaba-inc.com)（联系导师请附上个人简历）

**Comment by RinChanNOWWW** [comment]
Tracking:

- [x] EXZUNION：https://github.com/alibaba/TairZset/pull/8
- [x] EXZUNIONSTORE：https://github.com/alibaba/TairZset/pull/8
- [x] EXZDIFF：https://github.com/alibaba/TairZset/pull/10
- [x] EXZDIFFSTORE：https://github.com/alibaba/TairZset/pull/10
- [x] EXZINTER：https://github.com/alibaba/TairZset/pull/9
- [x] EXZINTERSTORE：https://github.com/alibaba/TairZset/pull/9
- [x] EXZSCAN：https://github.com/alibaba/TairZset/pull/7
- [x] EXZRANDMEMBER：https://github.com/alibaba/TairZset/pull/6
- [x] EXZMSCORE：https://github.com/alibaba/TairZset/pull/5
- [x] EXZPOPMAX: https://github.com/alibaba/TairZset/pull/14
- [x] EXZPOPMIN: https://github.com/alibaba/TairZset/pull/14
- [x] EXBZPOPMAX: https://github.com/alibaba/TairZset/pull/15
- [x] EXBZPOPMIN: https://github.com/alibaba/TairZset/pull/15
